# Generated by Django 5.2.7 on 2025-10-09 17:35

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "author_id",
                    models.BigIntegerField(
                        default=home.models.generate_user_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_name", models.CharField(max_length=50)),
                ("author_full_name", models.CharField(max_length=50)),
                ("author_email", models.CharField(max_length=50)),
                ("author_subject_a", models.CharField(blank=True, max_length=50)),
                ("author_subject_b", models.CharField(blank=True, max_length=50)),
                ("author_subject_c", models.CharField(blank=True, max_length=50)),
                ("author_subject_d", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "table_authors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "participant_id",
                    models.BigIntegerField(
                        default=home.models.generate_user_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("participant_name", models.CharField(max_length=50)),
                ("participant_full_name", models.CharField(max_length=50)),
                ("participant_email", models.CharField(max_length=50)),
                ("preferred_subject_a", models.CharField(blank=True, max_length=50)),
                ("preferred_subject_b", models.CharField(blank=True, max_length=50)),
                ("preferred_subject_c", models.CharField(blank=True, max_length=50)),
                ("preferred_subject_d", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "table_participants",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "question_id",
                    models.BigIntegerField(
                        default=home.models.generate_user_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                ("option_a", models.CharField(max_length=200)),
                ("option_b", models.CharField(max_length=200)),
                ("option_c", models.CharField(max_length=200)),
                ("option_d", models.CharField(max_length=200)),
                ("correct_option", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "table_questions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "quiz_id",
                    models.BigIntegerField(
                        default=home.models.generate_user_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={
                "db_table": "table_quizzes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QuizParticipant",
            fields=[
                (
                    "qp_id",
                    models.BigIntegerField(
                        default=home.models.generate_user_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_date", models.DateTimeField(auto_now_add=True)),
                ("score", models.FloatField(default=0.0)),
            ],
            options={
                "db_table": "table_quiz_participants",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "rating_id",
                    models.BigIntegerField(
                        default=home.models.generate_user_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating_value", models.IntegerField(default=0)),
                ("feedback", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "table_ratings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.BigIntegerField(
                        default=home.models.generate_user_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_name", models.CharField(max_length=50, unique=True)),
                ("user_password", models.CharField(max_length=50)),
                ("user_email", models.CharField(max_length=50, unique=True)),
                ("user_role", models.CharField(max_length=20)),
                ("user_status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "table_users",
                "managed": False,
            },
        ),
    ]
